databases:
  - name: graphleague_db
    plan: free
    databaseName: graphleague
    user: graphleague

services:
  - type: web
    plan: free
    name: graphleague
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn graphleague.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: graphleague_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4