# Generated by Django 4.2.13 on 2024-07-06 15:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champion', '0003_auto_20240511_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierList',
            fields=[
                ('riot_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='champion.champion')),
                ('games', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('picks', models.PositiveIntegerField(default=0)),
                ('bans', models.PositiveIntegerField(default=0)),
                ('platform', models.CharField(null=True)),
                ('synergy', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(null=True), size=None)),
            ],
        ),
    ]
