# Generated by Django 4.2.13 on 2024-06-14 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('game_name', models.CharField(null=True)),
                ('tag_line', models.CharField(null=True)),
                ('summoner_id', models.CharField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(null=True)),
                ('puuid', models.CharField(null=True)),
                ('profile_icon_id', models.CharField(null=True)),
                ('revision_date', models.CharField(null=True)),
                ('summoner_level', models.IntegerField(null=True)),
                ('region', models.CharField(null=True)),
                ('platform', models.CharField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
