# Generated by Django 4.2.13 on 2024-06-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together={('summoner_id', 'puuid')},
        ),
    ]
