# Generated by Django 4.2.13 on 2024-06-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together={('summoner_id', 'platform')},
        ),
    ]
