# Generated by Django 4.2.13 on 2024-05-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='extra',
        ),
    ]
