# Generated by Django 4.2.13 on 2024-05-11 10:44
from django.db import migrations
from champion.models import Champion


def initial_champion_loader(apps, schema_editor):
    # loads all the current champions into the database
    # schema_editor is needed to run pytest
    champion_model = apps.get_model("champion", "Champion")
    champions = Champion.champion_loader()

    for champion in champions:
        champion_model.objects.create(**champion)


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0002_remove_champion_extra'),
    ]

    operations = [
        migrations.RunPython(initial_champion_loader)
    ]
